Repository yashimwong/JSPhotoEditor, pull requests merged in 2020-10, with the labels that each got.

#2 Feature #1: Image Controls and Processing
  css/main.css
  index.html
  js/main.js
Labels: enhancement, hacktoberfest-accepted

#8 Fix filter values not returning to defaults on image load
  index.html
  js/main.js
Labels: hacktoberfest-accepted

#6 Added Image File Format Support - Initial Commit
  css/main.css
  index.html
  js/main.js
Labels: hacktoberfest-accepted

#12 Added compression option to image saving.
  index.html
  js/main.js
Labels: enhancement, hacktoberfest-accepted

#13 New UI Enhancement + Logo added
  css/main.css
  index_ui.html
  js/logo.ai
  media/logo.png
  tailwind.css
Labels: enhancement, hacktoberfest-accepted

#14 Implemented Shape Drawing Functionality
  .gitignore
  css/main.css
  index.html
  js/draw.js
Labels: enhancement, hacktoberfest-accepted

#15 Added exposure and contrast menu to enhanced UI
  index_ui.html
  js/main.js
Labels: enhancement, hacktoberfest-accepted

#16 Update draw.js to make triangles
  js/draw.js
Labels: bug, hacktoberfest-accepted
